# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_lista', models.CharField(max_length=50)),
                ('fecha_creacion_lista', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tarea', models.CharField(max_length=50)),
                ('terminado', models.BooleanField(default=False)),
                ('fecha_creacion_tarea', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('descipcion', models.TextField()),
                ('lista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tarea.Lista')),
            ],
        ),
    ]
