# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='descipcion',
            new_name='descripcion',
        ),
    ]
