# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0003_tarea_fecha_terminado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_terminado',
        ),
    ]
