# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0004_remove_tarea_fecha_terminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
